# fly.toml app configuration file generated for bot-vk on 2024-10-02T10:03:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-vk'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
